In [1]:
# ploting this figure needs raw data that we can't disclose, and we have uploaded the aggregated data that is able to reproduce the figure
import pandas as pd
import numpy as np
import csv
import math
import matplotlib.pyplot as plt
from pandas import Series,DataFrame
from matplotlib.ticker import  MultipleLocator

In [2]:
data = pd.read_excel('E:/vcdata/data/ALL_Intersection.xlsx')

In [3]:
data = data.fillna(0)
a = np.arange(2000,2018)
pop = [str(i)+'Pop' for i in a]
investment = [str(i)+'总投资金额(M)' for i in a]
inv_times = [str(i)+'总投资次数' for i in a]
gdp = [str(i)+'GDP' for i in a]

In [6]:
data.iloc[0:1,157-19:175-19]
157-19,175-19

(138, 156)

In [7]:
dataAmount = data.iloc[:,12:12+18]
dataTimes = data.iloc[0:,39:39+18]
dataGDP = data.iloc[:,157:175]
dataPOP = data.iloc[:,138:156]

In [8]:
def min2(data):
    minvalue = []
    for c in data.columns:
        s = data[c].values
        s = [i for i in s if i!=0]
        minvalue.append(min(s))
    return(minvalue)

In [9]:
len(min2(dataAmount))

18

In [11]:
a =list((dataAmount.shape[0] - (dataAmount == 0).astype(int).sum(axis=0)).values) + list((dataTimes.shape[0] - (dataTimes == 0).astype(int).sum(axis=0)).values)+list((dataGDP.shape[0] - (dataGDP == 0).astype(int).sum(axis=0)).values)

In [12]:
len(a)

54

In [13]:
df = pd.DataFrame()
df['year'] = np.arange(2000,2018)
df['size_Amount'] = list((dataAmount.shape[0] - (dataAmount == 0).astype(int).sum(axis=0)).values) 
df['size_deals'] = list((dataTimes.shape[0] - (dataTimes == 0).astype(int).sum(axis=0)).values)      
df['size_GMP'] = list((dataGDP.shape[0] - (dataGDP == 0).astype(int).sum(axis=0)).values)
df['size_POP'] = list((dataPOP.shape[0] - (dataPOP == 0).astype(int).sum(axis=0)).values)
df['mean_Amount'] = list(dataAmount.mean(axis=0).values)
df['mean_deals'] = list(dataTimes.mean(axis=0).values)
df['mean_GMP'] = list(dataGDP.mean(axis=0).values)
df['mean_POP'] = list(dataPOP.mean(axis=0).values)
df['SD_Amount'] = list(dataAmount.std(axis=0).values)
df['SD_deals'] = list(dataTimes.std(axis=0).values)
df['SD_GMP'] = list(dataGDP.std(axis=0).values)
df['SD_POP'] = list(dataPOP.std(axis=0).values)
df['max_Amount'] = list(dataAmount.max(axis=0).values)
df['max_deals'] = list(dataTimes.max(axis=0).values)
df['max_GMP'] = list(dataGDP.max(axis=0).values)
df['max_POP'] = list(dataPOP.max(axis=0).values)
# df['min'] = data3.min2(axis=0)[9:9+18].values
df['min_Amount'] = min2(dataAmount)
df['min_deals'] = min2(dataTimes)
df['min_GMP'] = min2(dataGDP)
df['min_POP'] = min2(dataPOP)
df['sum_Amount'] = list(dataAmount.sum(axis=0).values)
df['sum_deals'] = list(dataTimes.sum(axis=0).values)
df['sum_GMP'] = list(dataGDP.sum(axis=0).values)
df['sum_POP'] = list(dataPOP.sum(axis=0).values)

In [14]:

df.to_csv('E:/vcdata/meanSD.csv')

In [15]:
################################################

In [16]:
########## 求所有去拟合的GDP、amount、times 的均值之类的指标 ###########
a = np.arange(2000,2018)
pop = [str(i)+'Pop' for i in a]
investment = [str(i)+'总投资金额(M)' for i in a]
inv_times = [str(i)+'总投资次数' for i in a]
gdp = [str(i)+'GDP' for i in a]
pop = [str(i)+'Pop' for i in a]

In [17]:
### 对城市进行分类，大城市记为1，非大城市记为0.
pop17 = data['2017Pop'].values
data['popType_0']=pop17
data['popType_1']=pop17
for i in range(len(pop17)):
        if pop17[i] < 550:
            data['popType_0'][i]=1###小城市
            data['popType_1'][i]=0###小城市
        else:
            data['popType_0'][i]=0###特大城市
            data['popType_1'][i]=1###特大城市

D:\Users\lu\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
D:\Users\lu\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
D:\Users\lu\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
D:\Users\lu\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning: 
A

In [18]:
### 获得双对数的值 ，舍掉双对数中的0值###
def get_log3(inv,g,DATA,name):
    x = DATA[inv]
    y = DATA[g]
    y_investment=np.log10(DATA[inv])
    y_gdp=np.log10(DATA[g])
    y_investment2=y_investment.fillna(np.infty)
    y_gdp2=y_gdp.fillna(np.infty)
    types = DATA[name]
    x1=[]
    y1=[]
    X = []
    Y = []
    Types = []
    for xi in range(len(y_investment2)):
        if y_investment2[xi]==-float('Inf') or y_investment2[xi]==float('Inf') or y_gdp2[xi]==-float('Inf') or y_gdp2[xi]==float('Inf'):
            continue
        else:
            x1.append(y_investment2[xi])
            y1.append(y_gdp2[xi])
            Types.append(types[xi]*y_investment2[xi])
            X.append(x[xi])
            Y.append(y[xi])
    return(x1,y1,Types,X,Y)

In [25]:
#### 计算所有年amount、times、GDP的均值之类的指标
def getmean(amount):
    df = pd.DataFrame()
    df['amount'] = amount
    size = (df.shape[0] - (df == 0).astype(int).sum(axis=0)).values
    mean = df.mean(axis=0).values
    SD = df.std(axis=0).values
    maxvalues = df.max(axis=0).values
    minvalues = df.min(axis=0).values
    return(size,mean,SD,maxvalues,minvalues)

In [119]:
######## 所有年份所有数据分类，大城市为1，其他城市为0
POP = []### 所有城市所有年份的人口
AMountB = []###所有城市所有年份的投资金额
TYPE0 = []
TYPE1=[]
TimesB = []
GDPB = []
for i in range(18):
    X11=pop[i]
    X21=investment[i]
    X22=inv_times[i]
    X23=gdp[i]
    Y1 = get_log3(X11,X21,data,'popType_0')
    Y2 = get_log3(X11,X21,data,'popType_1')
    Y22 = get_log3(X11,X22,data,'popType_1')
    Y23 = get_log3(X11,X23,data,'popType_1')
    POP += Y1[3]
    AMountB += Y1[4]
    TimesB += Y22[4]
    GDPB += Y23[4]
#     Y_total = get_log(X11,X21,data)

D:\Users\lu\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log10
  """
D:\Users\lu\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log10
  


In [120]:
######## 所有年份所有数据分类，大城市为1，其他城市为0
POP = []### 所有城市所有年份的人口
AMount = []###所有城市所有年份的投资金额
TYPEyear0 = []
TYPEyear1=[]
Times = []
GDP = []
a = np.arange(2000,2018)
yearType = [str(i)+'yearType0' for i in a]### 2013年之前的为0
yearType2 = [str(i)+'yearType1' for i in a]###2013年之前的为1
for i in range(18):
    if i<13:
        data[yearType[i]] = [0]*data.shape[0]
        data[yearType2[i]] = [1]*data.shape[0]
    else:
        data[yearType[i]] = [1]*data.shape[0]
        data[yearType2[i]] = [0]*data.shape[0]
    X11=pop[i]
    X21=investment[i]
    X22=inv_times[i]
    X23=gdp[i]
    Y1 = get_log3(X11,X21,data,yearType[i])
    Y2 = get_log3(X11,X21,data,yearType2[i])
    Y12 = get_log3(X11,X22,data,yearType[i])
    Y13 = get_log3(X11,X23,data,yearType2[i])
    AMount += Y1[4]
    Times += Y12[4]
    GDP += Y13[4]
#     Y_total = get_log(X11,X21,data)

D:\Users\lu\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log10
  """
D:\Users\lu\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log10
  


In [121]:
dataAmount = getmean(AMount)
dataTimes = getmean(Times)
dataGDP = getmean(GDP)

dataAmountB = getmean(AMountB)
dataTimesB = getmean(TimesB)
dataGDPB = getmean(GDPB)

In [ ]:
size = []
mean = []
SD = []
maxvalues = []
minvalues = []
    size + = list(dataAmountB[0])+

In [125]:
list(dataAmountB[0]) + list(dataTimesB[0])

[1780, 1961]

In [126]:
DF = pd.DataFrame()
DF['size'] = list(dataAmountB[0]) + list(dataTimesB[0])+list(dataGDPB[0])
DF['mean'] = list(dataAmountB[1]) + list(dataTimesB[1])+list(dataGDPB[1])
DF['SD'] = list(dataAmountB[2]) + list(dataTimesB[2])+list(dataGDPB[2])
DF['max'] = list(dataAmountB[3]) + list(dataTimesB[3])+list(dataGDPB[3])
DF['min'] = list(dataAmountB[4]) + list(dataTimesB[4])+list(dataGDPB[4])

In [128]:
DF.index = ['Amount','# deals','GMP']

In [129]:
DF

size          mean            SD           max           min
Amount   1780  1.183424e+03  6.383987e+03  1.079785e+05       0.17118
# deals  1961  1.880571e+01  9.458203e+01  1.810000e+03       1.00000
GMP      4790  8.537716e+06  2.096082e+07  3.063299e+08  103847.00000

In [130]:
DF.to_csv('E:/vcdata/AllmeanSD.csv')

In [131]:
######### 所有数据 2000-2017年的指标 ##########

In [19]:
Data = pd.read_excel('E:/vcdata/vcdata(91-17-new).xlsx')
Data2 = pd.read_excel('E:/vcdata/00-18POP&GDP.xlsx')

In [20]:
Data.shape[0],Data2.shape[0],Data2.columns

(46775,
 276,
 Index(['City', '2000Pop', '2001Pop', '2002Pop', '2003Pop', '2004Pop',
        '2005Pop', '2006Pop', '2007Pop', '2008Pop', '2009Pop', '2010Pop',
        '2011Pop', '2012Pop', '2013Pop', '2014Pop', '2015Pop', '2016Pop',
        '2000GDP', '2001GDP', '2002GDP', '2003GDP', '2004GDP', '2005GDP',
        '2006GDP', '2007GDP', '2008GDP', '2009GDP', '2010GDP', '2011GDP',
        '2012GDP', '2013GDP', '2014GDP', '2015GDP', '2016GDP', '2017Pop',
        '2017GDP', '2018Pop', '2018GDP'],
       dtype='object'))

In [21]:
len(list(Data2['2000Pop'])+list(Data2['2001Pop']))

552

In [23]:
Data = Data.fillna(0)
amounAll = [i if i!='--' else 0 for i in Data['投资金额(RMB)']]
timesAll = [1 if i!='--' and i!=0 else 0 for i in Data['投资金额(RMB)']]
GDPAll = []
POPAll = []
for i in range(len(gdp)):
    GDPAll += list(Data2[gdp[i]]/100)
    POPAll += list(Data2[pop[i]])

In [26]:
dataAmountAll = getmean(amounAll)
dataTimesAll = getmean(timesAll)
dataGDPAll = getmean(GDPAll)
dataPOPAll = getmean(POPAll)

In [28]:
dataPOPAll

(array([4968], dtype=int64),
 array([108.37268946]),
 array([197.25053302]),
 array([2425.68]),
 array([4.]))

In [173]:
dataAmountAll

(array([37309], dtype=int64),
 array([62.59454044]),
 array([429.49485785]),
 array([29327.259438]),
 array([0.]))

In [29]:
DFall = pd.DataFrame()
DFall['size'] = list(dataAmountAll[0]) + list(dataTimesAll[0])+list(dataGDPAll[0])+list(dataPOPAll[0])
DFall['mean'] = list(dataAmountAll[1]) + list(dataTimesAll[1])+list(dataGDPAll[1])+list(dataPOPAll[1])
DFall['SD'] = list(dataAmountAll[2]) + list(dataTimesAll[2])+list(dataGDPAll[2])+list(dataPOPAll[2])
DFall['max'] = list(dataAmountAll[3]) + list(dataTimesAll[3])+list(dataGDPAll[3])+list(dataPOPAll[3])
DFall['min'] = list(dataAmountAll[4]) + list(dataTimesAll[4])+list(dataGDPAll[4])+list(dataPOPAll[4])

In [31]:
DFall.index = ['Amount','# deals','GMP','Population']
DFall.to_csv('E:/vcdata/0AllDatameanSD.csv')

In [32]:
DFall

size          mean             SD           max      min
Amount      37309     62.594540     429.494858  2.932726e+04     0.00
# deals     37309      0.797627       0.401773  1.000000e+00     0.00
GMP          4968  84231.017371  208083.935237  3.063299e+06  1038.47
Population   4968    108.372689     197.250533  2.425680e+03     4.00

In [176]:
DFall

size          mean             SD           max      min
0  37309     62.594540     429.494858  2.932726e+04     0.00
1  37309      0.797627       0.401773  1.000000e+00     0.00
2   4968  84231.017371  208083.935237  3.063299e+06  1038.47